server:
  port: 8989
  servlet:
    context-path: /excel

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/datasource?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username:
    password:
  application:
    name: springboot-scheduled
  mail:
    host: smtp.163.com
    username:
    password:
    port: 994
    default-encoding: UTF-8
    protocol: smtps
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
    from:
file:
  download:
    dir:


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.demo.entity

logging:
  level:
    com.example.demo.TaskController: debug
    com.example.demo.EmailServiceImpl: debug
    com.example.demo.EmailService: debug
    com.example.demo.dao: debug